server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE


spring:
  jackson:
    time-zone: America/Guayaquil
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2
      idle-timeout: 30000
      connection-timeout: 20000
      housekeeping-period: 10000
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

gmail:
  address: ${GMAIL_SENDER_ADDRESS}
  password: ${GMAIL_SENDER_PASSWORD}
  
aws:
  region: ${AWS_REGION}
  cognito:
    userPoolId: ${AWS_COGNITO_USERPOOLID}
    clientId: ${AWS_COGNITO_CLIENTID}
  sns:
    platformApplicationArnAndroid: ${AWS_SNS_PLATFORMAPPLICATIONARNANDROID}

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

encryption:
  key: ${ENCRYPTION_KEY}
